[project]
name = "cica-document-search-airflow"
version = "0.1.0"
description = ""
authors = [{ name = "Marco Surace" }]
requires-python = ">=3.12,<4"
readme = "README.md"
dependencies = [
    "opensearch-py>=3.0.0,<4.0.0",
    "pydantic-settings>=2.10.1,<3.0.0",
    "pydantic (>=2.12.3,<3.0.0)",
    "amazon-textract-textractor (>=1.9.2,<2.0.0)",
    "boto3 (>=1.40.57,<2.0.0)",
    "amazon-textract-caller (>=0.2.4,<0.3.0)",
]

[dependency-groups]
test = [
    "pytest-mock>=3.15.1,<4",
    "pytest>=8.4.1,<9",
    "pytest-cov>=6.2.1,<8",
    "moto>=5.1.10,<6",
]
dev = ["deptry>=0.23.1,<0.24", "numpy>=2.3.4", "pre-commit>=4.2.0,<5"]

[tool.uv]
default-groups = ["test", "dev"]

[tool.hatch.build.targets.sdist]
include = ["src/ingestion_pipeline"]

[tool.hatch.build.targets.wheel]
include = ["src/ingestion_pipeline"]

[tool.hatch.build.targets.wheel.sources]
"src/ingestion_pipeline" = "ingestion_pipeline"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
